#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/weblinc/facebook/engine', __FILE__)

require 'rails'

%w(action_controller action_view action_mailer sprockets).each do |framework|
  begin
    require "#{framework}/railtie"
  rescue LoadError
  end
end

require 'rails/engine/commands'
